
export const homeObjOne = {
    id: 'about',
    lightBg:false,
    lightText:true,
    lightTextDesc:true,
    topLine:'Premium Bank',
    headline: 'Unlimited Transactions with zero fees',
    description: 'Get access to our exclusive app that allows you to send unlimited transaction without getting charged any fees.',
    buttonLabel:'Get Started',
    imgStart:false,
    img:require('../../images/undraw_delivery_truck_vt6p.png'),
    alt:'car',
    dark:true,
    primary:true,
    darkText:false,
}; 
export const homeObjTwo = {
    id: 'discover',
    lightBg:true,
    lightText:false,
    lightTextDesc:false,
    topLine:'Unlimited Access',
    headline: 'Login to your account at any time',
    description: 'We have you covered no matter where you are located. All you need is an internet connection and a phone or computer.',
    buttonLabel:'Learn More',
    imgStart:true,
    img:require('../../images/undraw_factory_dy0a.png'),
    alt:'car',
    dark:false,
    primary:false,
    darkText:true,
}; 
export const homeObjThree = {
    id: 'signup',
    lightBg:true,
    lightText:false,
    lightTextDesc:false,
    topLine:'Join our Team',
    headline: 'Creating an account is extremely easy',
    description: 'Get everything set up and ready in under 10 minutes. All you need to do is add your information and you are ready to go',
    buttonLabel:' Start Now',
    imgStart:false,
    img:require('../../images/undraw_online_transactions_02ka.png'),
    alt:'car',
    dark:false,
    primary:false,
    darkText:true,
}; 
